#!/bin/bash

TMPL_CC="`dirname $0`/tmpl_cc"
TMPL_AS="`dirname $0`/tmpl_as"

while [ "$1" == "-p" ] || [ "$1" == "-o" ] 
do
	if [ "$1" == "-p" ] ; then
		POT="$2"
	else
		TNAME="$2"
	fi
	shift
	shift
done

if [ "$TNAME" == "" ] ; then
	echo "Usage: tmpl_bld -o template.opcode [ -p template.pot ] template1.tmpl ... "
	exit 1
fi


SNAME=${TNAME%.opcode}.s

RES=0

shift
if $TMPL_CC $@ >"$SNAME" ; then
	if [ "$POT" == "" ] && $TMPL_AS "$TNAME" <"$SNAME" ; then
		RES=0
	elif [ "$POT" != "" ] && $TMPL_AS "$TNAME" "$POT" <"$SNAME" ; then
		RES=0
	else
		echo "Assembly failed"
		RES=1
	fi
else
	echo "Compilation failed"
	RES=1
fi

exit $RES
