#!/bin/bash

down()
{
	kill $1
	kill $2
	wait $1
	wait $2
	echo "done"
	exit
}

./cppblog -c config-local.txt &
SERVER=$!

thttpd -D -p 8080 -c '/blog' -h localhost &
PROCESS=$!

trap "echo signal... ; down $SERVER  $PROCESS " SIGHUP SIGINT SIGTERM

echo "Press any key to exit"
read
down $SERVER  $PROCESS


